wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715905677
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 19
      - 23
      4: 3.11.7
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 100
