name: train_model_cml
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          pip install -r requirements.txt
          python train_model_cml.py
      - name: Write Report
        env:
          REPO_TOKEN= ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat classification_report.txt >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md
